# Generated by Django 5.2.3 on 2025-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID чата в Telegram"
            ),
        ),
    ]
