# Generated by Django 5.2.3 on 2025-06-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="associted_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Привычка, которая связана с полезной привычкой (не с приятной)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
